using System;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace Mongo.Models
{
        public class Note
    {
/*         [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }      */           

        // external ID or key, which may be easier to reference (ex: 1,2,3 etc.)
        [BsonId]
        public string Id { get; set; }                           

        public string Body { get; set; } = string.Empty;
        public DateTime UpdatedOn { get; set; } = DateTime.Now;
        public DateTime CreatedOn { get; set; } = DateTime.Now;
        public int UserId { get; set; } = 0;
    }
}